### PR TITLE
Fix WS URL on browsers

### LINKED ISSUE #46: [Logs] Broken path for WS on app Logs

### PR DESCRIPTION
**Pull request by johnsudaar**
Fix #46

### CODE REVIEW

File: src/Logs/listener.js [hunk 1]
```diff
@@ -8,8 +8,14 @@ export default class LogsListener {
    */
 
   constructor(client, url) {
+    let wsURL = new URL(url)
+    if(wsURL.protocol == "http:" || wsURL.protocol == "ws:") {
+      wsURL.protocol = "ws"
```
Comment (EtienneM) [inline src/Logs/listener.js]: The above line specify that the protocol includes the `:` but here your protocol does NOT include the `:`. Are you sure it will work?

Comment (johnsudaar) [reply src/Logs/listener.js]: Yes:

```
let url = new URL("https://test.fr")
> undefined
url.protocol
> "https:"
url.protocol = "wss"
> "wss"
url.toString()
> "wss://test.fr/"

Comment (EtienneM) [reply src/Logs/listener.js]: Well.... That's confusing.
I :heart: JS!
